language: emacs-lisp
addons:
  apt:
    sources:
      # stable emacs
      - cassou-emacs
    packages:
      - emacs24-nox
      - python
cache:
  directories:
    - $HOME/.cask
    - $HOME/.twister
before_install:
  #- sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # emacs-el ? needed for what?
  - if [ ! -d $HOME/.cask ];then curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python; fi
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
env:
  - EMACS=emacs24
script:
  - emacs --version
  - make test

