language: emacs-lisp
addons:
  apt:
    sources:
      # stable emacs
      - cassou-emacs
    packages:
      - emacs24-nox
      - python
cache:
  directories:
    - $HOME/.twister
before_install:
  # emacs-el ? needed for what?
  # Install cask and run it to install the emacs dependency packages
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
env:
  - EMACS=emacs24
script:
  - emacs --version
  - make test

